# Generated by Django 5.0.3 on 2024-03-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('celular', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
    ]
