# Generated by Django 5.0.3 on 2024-03-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_cargos_estados_alter_funcionarios_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='email',
            field=models.CharField(default='fulano@email.com', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='salario',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
