# Generated by Django 5.0.3 on 2024-03-06 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_linguagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='linguagem',
            field=models.ManyToManyField(limit_choices_to=5, to='staff.linguagens'),
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.estados'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='cargo',
            field=models.ManyToManyField(to='staff.cargos'),
        ),
    ]
