# Generated by Django 5.0.3 on 2024-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_linguagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='linguagem',
            field=models.ManyToManyField(limit_choices_to=5, to='staff.linguagens'),
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='estado',
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='cargo',
            field=models.ManyToManyField(to='staff.cargos'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='estado',
            field=models.ManyToManyField(to='staff.estados'),
        ),
    ]
