# Generated by Django 5.0.3 on 2024-03-28 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_funcionarios_linguagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senioridade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.ManyToManyField(related_name='cargos', to='staff.cargos'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estado', to='staff.estados'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='linguagem',
            field=models.ManyToManyField(related_name='linguagem', to='staff.linguagens'),
        ),
    ]
