# Generated by Django 5.0.3 on 2024-03-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_senioridade_alter_funcionarios_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='senioridade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='senioridade', to='staff.senioridade'),
            preserve_default=False,
        ),
    ]
