# Generated by Django 5.0.3 on 2024-04-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_funcionarios_senioridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cargo',
            field=models.ManyToManyField(related_name='funcionarios', to='staff.cargos'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='staff.estados'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='linguagem',
            field=models.ManyToManyField(related_name='funcionarios', to='staff.linguagens'),
        ),
        migrations.AlterField(
            model_name='funcionarios',
            name='senioridade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='staff.senioridade'),
        ),
    ]
