# Generated by Django 5.0.3 on 2024-04-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_funcionarios_cargo_alter_funcionarios_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='cargo',
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='staff.cargos'),
            preserve_default=False,
        ),
    ]
